name: McTelemetry4J

services:
  telemetry_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemetry_backend
    ports:
      - "8082:8080"
    restart: unless-stopped
    depends_on:
      - telemetry_db
    environment:
      MYSQL_HOST: telemetry_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: my_database
      MYSQL_USERNAME: my_user
      MYSQL_PASSWORD: my_password

  telemetry_db:
    image: mysql:8.0
    container_name: telemetry_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

networks:
  default:

volumes:
  db_data:
    name: mctelemetry4j_db_data
